### ISSUE TITLE
Need to rename - existing Dart network_manager package

### ISSUE THREAD

**Issue by robert-ancell** [canonical/networkmanager.dart#1]
There is an existing [`network_manager`](https://pub.dev/packages/network_manager) package, so this needs a new name. Suggestions:
-`nm`
-`nmclient`
-`nm_client`
-`network_manager_client`
-`networkmanager`
-`fdo_network_manager`

**Comment by kenvandine** [comment]
Would it be useful to have just a simplified connectivity package that provides simple state info, like connected and what kind of connection?

Do we need a full-fledged network-manager client package?

**Comment by kenvandine** [comment]
If we want a package for this, then I'd vote for networkmanager

**Comment by robert-ancell** [comment]
Yeah, I think `networkmanager` is the best name out of the options. Renamed.

I don't think we need a full network-manager client right now, but the way the D-Bus API works is you get all the state together, so we might as well make a package that can do everything. We don't need to fill out all the properties/methods right now though (or at all if there's no demand).

**Comment by robert-ancell** [comment]
When I try to upload:
`Package name is too similar to another active or moderated package.`

**Comment by robert-ancell** [comment]
I've emailed the developer to ask if they'd consider renaming - their project is only one month old and not depended on by anything at this time.

**Comment by long1eu** [comment]
network_manager_dbus
network_manager_linux

**Comment by robert-ancell** [comment]
Renamed to 'nm'.
