### ISSUE TITLE
Does getting ARP TABLE belong in this package

### ISSUE THREAD

**Issue by guyluz11** [canonical/networkmanager.dart#66]
I am searching for a way to get ARP TABLE on different platforms for one of my apps.

Will it be the correct place to create future requests to add support for getting ARP TABLE on Linux?.

**Comment by robert-ancell** [comment]
Network Manager doesn't provide any information on ARP, to get this on Linux you will need to make a [system call](https://man7.org/linux/man-pages/man7/arp.7.html) via FFI. You may want to do that directly or make use of an existing Dart library that has implemented this (I don't know if any have).
