### ISSUE TITLE
How to check for wireless scan availability

### ISSUE THREAD

**Issue by mortenboye** [canonical/networkmanager.dart#7]
I would like to search for and connect to a wireless network.

It seems that calling `device.wireless.requestScan();` too often will result in `org.freedesktop.NetworkManager.Device.NotAllowed`
Is there are way to tell if the scan is possible or busy?

Having discovered a network, how do i connect to it wirelessly?

**Comment by robert-ancell** [comment]
@mortenboye you'll need to consult the [NetworkManager D-Bus API documentation](https://developer.gnome.org/NetworkManager/stable/spec.html) for the exact calls you need to make.

But essentially `requestScan` should be called once and you wait for the `LastScan` property to update ([documentation)](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.Wireless.html#gdbus-method-org-freedesktop-NetworkManager-Device-Wireless.RequestScan)).

I'm not familiar enough with the NetworkManager D-Bus API, so hopefully you can work out the method of connecting to a WiFi network.
